# Generated by Django 4.2.3 on 2023-07-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0002_cart_cartitem_delete_shoppingcart_cart_items_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_item_cart',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('item', 'cart'), name='unique_item_cart'),
        ),
    ]
