# Generated by Django 4.2.3 on 2023-07-12 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0005_remove_cart_user_cart_number_of_items_cart_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='bookstore_app.cart'),
        ),
    ]
